import React from "react";
import {
  EuiProvider,
  EuiFlexGroup,
  EuiFlexItem,
  EuiCard,
  EuiImage,
} from "@elastic/eui";
import { useNavigate } from "react-router-dom";
import useAuth from "../hooks/useAuth";
import create from "../assets/create.svg";
import Header from "../components/Header";

const UserDashboard = () => {
  useAuth();
  const navigate = useNavigate();
  return (
    <EuiProvider colorMode="dark">
      <div
        style={{ display: "flex", height: "100vh", flexDirection: "column" }}
      >
        <Header />
        <EuiFlexGroup
          justifyContent="center"
          alignItems="center"
          style={{ margin: "7vh 10vw" }}
        >
          <EuiFlexItem>
            <EuiCard
              icon={<EuiImage size="5rem" alt="image" src={create} />}
              title={"Meetings"}
              description="Here your stored data for video conferences with others are stored . Join at your own pace! "
              onClick={() => navigate("/meetings")}
              paddingSize="xl"
            />
          </EuiFlexItem>
          <EuiFlexItem>
            <EuiCard
              icon={<EuiImage size="7rem" alt="image" src={create} />}
              title={"Generate Meet"}
              description="Generate video call for the others and invite them for a 1-on-1 OR Video Conference"
              onClick={() => navigate("/create")}
              paddingSize="xl"
            />
          </EuiFlexItem>
          <EuiFlexItem>
            <EuiCard
              icon={<EuiImage size="5rem" alt="image" src={create} />}
              title={" My Meetings"}
              description="Meets for others are stored which was generated by you. "
              onClick={() => navigate("/mymeetings")}
              paddingSize="xl"
            />
          </EuiFlexItem>
          {/* <EuiFlexItem>
            <EuiCard
              icon={<EuiImage size="5rem" alt="image" src={create} />}
              title={"Engage Time"}
              description="Card Description"
              onClick={() => navigate("/engage")}
              paddingSize="xl"
            />
          </EuiFlexItem> */}
        </EuiFlexGroup>
        <EuiCard
          // icon={<EuiImage size="1rem" alt="image" src={create} />}
          title={"Engage Time"}
          description="Use your free time to gain some more knowlegde about the "
          onClick={() => navigate("/engage")}
          paddingSize="xl"
        />
      </div>
    </EuiProvider>
  );
};

export default UserDashboard;
